### ISSUE TITLE
Release Release v0.2.10 · setuid_sandbox_host.cc(158) error

### ISSUE THREAD

**Issue by anaxareian** [juntofoundation/flux#168]
This is the message I see on start if I try and run with no arguments. 

> $ ./Flux-0.2.10.AppImage
>  [18278:1027/152043.832936:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Flux-0NRwwhl/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap

If I try and run with '--no-sandbox' I see the below.  It includes the stacktrace of where I am waiting after a ^C is sent.  The first time I ran it, I got past the splash screen to an Error screen, but I closed that after clicking the [Copy] button.  I then found it failed to copy any data to thee clipboard.  So, the below is from a following re-execution, and is a slightly different result at least in the UI. 

> $ ./Flux-0.2.10.AppImage --no-sandbox
>  App is running in production mode  
> 
> (node:18379) Warning: Accessing non-existent property 'abort' of module exports inside circular dependency
> (Use `flux --trace-warnings ...` to show where the warning was created)
> 
> UserData path
> /home/aia/.config/flux
> 
> AppData path
> /home/aia/.config
> 
> Log path
> /home/aia/.config/flux/logs
> 
> Using Resource path
> /tmp/.mount_Flux-0blg8Qu/resources/packaged-resources/bin
> 
> built in language path
> 
> /tmp/.mount_Flux-0blg8Qu/resources/packaged-resources/languages
> %s
> Init AD4M...
> 
> 
> Starting ad4m core with path:
> /home/aia/.config/flux
> 
> 
> AD4M Bootstrap Languages:
> {
>   agents: 'agent-expression-store',
>   languages: 'languages',
>   neighbourhoods: 'neighbourhood-store'
> }
> 
> 
> Built-in languages path:
> /tmp/.mount_Flux-0blg8Qu/resources/packaged-resources/languages
> 
> 
> Built-In languages:
> [ 'direct-message-language' ]
> 
> 
> => All auto-loaded languages:
> [
>   'agent-expression-store',
>   'languages',
>   'neighbourhood-store',
>   'direct-message-language'
> ]
> 
> 
> Language aliases:
> {
>   did: 'agent-expression-store',
>   lang: 'languages',
>   neighbourhood: 'neighbourhood-store'
> }
> 
> 
> Resource path:
> /tmp/.mount_Flux-0blg8Qu/resources/packaged-resources/bin
> 
> 
> 
> 
> Init services...
> 
> Init HolochainService with data path: 
> /home/aia/.config/flux/ad4m/h/d
> . Conductor path: 
> /home/aia/.config/flux/ad4m/h/c
> . Resource path: 
> /tmp/.mount_Flux-0blg8Qu/resources/packaged-resources/bin
> Holochain ports: admin=2000 app=1337
> HolochainService: Creating low-db instance for holochain-serivce
> /tmp/.mount_Flux-0blg8Qu/resources/packaged-resources/bin/lair-keystore: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Flux-0blg8Qu/resources/packaged-resources/bin/lair-keystore)
> 
> Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
> Swarm listening on /ip4/10.0.0.64/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
> Swarm listening on /ip4/192.168.100.213/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
> Swarm listening on /ip4/10.11.12.16/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
> Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
> IPFS Version:
> 0.10.8
> 
> ^Cbefore-quit SIGNAL
> Unhandled Rejection at: Promise
> Promise {
>   <rejected> TypeError: Cannot read properties of undefined (reading 'webContents')
>       at /tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:409556
>       at l (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:205397)
>       at Generator._invoke (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:205150)
>       at Generator.next (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:205760)
>       at l (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397580)
>       at s (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397783)
>       at /tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397842
>       at new Promise (<anonymous>)
>       at App.<anonymous> (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397723)
>       at App.emit (node:events:394:28)
> }
> reason:
> TypeError: Cannot read properties of undefined (reading 'webContents')
>     at /tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:409556
>     at l (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:205397)
>     at Generator._invoke (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:205150)
>     at Generator.next (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:205760)
>     at l (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397580)
>     at s (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397783)
>     at /tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397842
>     at new Promise (<anonymous>)
>     at App.<anonymous> (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397723)
>     at App.emit (node:events:394:28)
> (node:18379) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'webContents')
>     at /tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:409556
>     at l (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:205397)
>     at Generator._invoke (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:205150)
>     at Generator.next (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:205760)
>     at l (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397580)
>     at s (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397783)
>     at /tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397842
>     at new Promise (<anonymous>)
>     at App.<anonymous> (/tmp/.mount_Flux-0blg8Qu/resources/app.asar/background.js:2:397723)
>     at App.emit (node:events:394:28)
> (node:18379) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 87)
> will-quit SIGNAL
> aia@DellE6530:~/apps/flux$ ./Flux-0.2.10.AppImage --no-sandbox^C
> aia@DellE6530:~/apps/flux$ ./Flux-0.2.10.AppImage 
> [18653:1027/152640.959582:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Flux-0bP1ODN/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap
> aia@DellE6530:~/apps/flux$ ./Flux-0.2.10.AppImage --no-sandbox
>  App is running in production mode  
> 
> (node:18708) Warning: Accessing non-existent property 'abort' of module exports inside circular dependency
> (Use `flux --trace-warnings ...` to show where the warning was created)
> 
> UserData path
> /home/aia/.config/flux
> 
> AppData path
> /home/aia/.config
> 
> Log path
> /home/aia/.config/flux/logs
> 
> Using Resource path
> /tmp/.mount_Flux-0f64hWc/resources/packaged-resources/bin
> 
> built in language path
> 
> /tmp/.mount_Flux-0f64hWc/resources/packaged-resources/languages
> %s
> Init AD4M...
> 
> 
> Starting ad4m core with path:
> /home/aia/.config/flux
> 
> 
> AD4M Bootstrap Languages:
> {
>   agents: 'agent-expression-store',
>   languages: 'languages',
>   neighbourhoods: 'neighbourhood-store'
> }
> 
> 
> Built-in languages path:
> /tmp/.mount_Flux-0f64hWc/resources/packaged-resources/languages
> 
> 
> Built-In languages:
> [ 'direct-message-language' ]
> 
> 
> => All auto-loaded languages:
> [
>   'agent-expression-store',
>   'languages',
>   'neighbourhood-store',
>   'direct-message-language'
> ]
> 
> 
> Language aliases:
> {
>   did: 'agent-expression-store',
>   lang: 'languages',
>   neighbourhood: 'neighbourhood-store'
> }
> 
> 
> Resource path:
> /tmp/.mount_Flux-0f64hWc/resources/packaged-resources/bin
> 
> 
> 
> 
> Init services...
> 
> Init HolochainService with data path: 
> /home/aia/.config/flux/ad4m/h/d
> . Conductor path: 
> /home/aia/.config/flux/ad4m/h/c
> . Resource path: 
> /tmp/.mount_Flux-0f64hWc/resources/packaged-resources/bin
> Holochain ports: admin=2000 app=1337
> HolochainService: Creating low-db instance for holochain-serivce
> /tmp/.mount_Flux-0f64hWc/resources/packaged-resources/bin/lair-keystore: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Flux-0f64hWc/resources/packaged-resources/bin/lair-keystore)
> 
> Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
> Swarm listening on /ip4/10.0.0.64/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
> Swarm listening on /ip4/192.168.100.213/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
> Swarm listening on /ip4/10.11.12.16/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
> Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
> IPFS Version:
> 0.10.8
> 

And, I never get past the flux splash screen.

My  system is Bunsen Linux, a Debian variant.

> $ uname -a
> Linux DellE6530 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

> $ uname -a
> Linux DellE6530 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

**Comment by anaxareian** [comment]
Hey Joshua,

Happy All Saints Day!

I finally got around to upgrading my Debian system to Bullseye, the current testing.  

Now my linker is newer than what you suggested:



$ ldd --version
ldd (Debian GLIBC 2.31-13+deb11u2) 2.31


Should I see if I can load that specific version of GLIBC, or do you think any newer
version than the one you recommend will be OK?

Sorry, but I am flying quite blind here.  

Sincerely, 

aia
--
True wisdom is less presuming than folly. 
The wise man doubteth often, and changeth his mind; 
the fool is obstinate, and doubteth not; he knoweth all things,
but his own ignorance.  

 

    On Thursday, October 28, 2021, 02:49:26 PM EDT, Anaxareian Aia ***@***.***> wrote:  
 
 Thanks!  I'll look into it.  I really appreciate your time and attention. 
--
True wisdom is less presuming than folly. 
The wise man doubteth often, and changeth his mind; 
the fool is obstinate, and doubteth not; he knoweth all things,
but his own ignorance.  

 

    On Thursday, October 28, 2021, 09:33:13 AM EDT, Joshua Parkin ***@***.***> wrote:  
 
 


I can see that we are trying to start the lair-keystore binary but it is reporting that GLIBC_2.29 is not found. Are you able to install this version of GLIBC? I guess it might mean upgrading your linux version to one which supports a newer GLIBC version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jdeepee** [comment]
@anaxareian great, id give the release a go and hopefully that should avoid you having to compile the app yourself :)

**Comment by anaxareian** [comment]
The app is running now.  TY!

aia
--
True wisdom is less presuming than folly. 
The wise man doubteth often, and changeth his mind; 
the fool is obstinate, and doubteth not; he knoweth all things,
but his own ignorance.  

 

    On Wednesday, November 3, 2021, 11:00:04 AM EDT, Joshua Parkin ***@***.***> wrote:  
 
 


@anaxareian great, id give the release a go and hopefully that should avoid you having to compile the app yourself :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
