### ISSUE TITLE
Build Fails on Debian Bullseye

### ISSUE THREAD

**Issue by anaxareian** [juntofoundation/flux#170]
I moved from Buster to Bullseye because someone suggested the Buster linker was too old.  Now I am using a newer linker than what was recommended, so it may still be an issue.  

## System
> $ cat /etc/issue
> Debian GNU/Linux 11 \n \l

> $ uname -a 
> Linux DellE6530 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

> ldd --version
> ldd (Debian GLIBC 2.31-13+deb11u2) 2.31

## Errors

>    Compiling pin-project-internal v1.0.8
> error: linking with `/nix/store/88ghxafjpqp5sqpd75r51qqg4q5d95ss-gcc-wrapper-10.3.0/bin/cc` failed: exit status: 1
>   |
>   = note: "/nix/store/88ghxafjpqp5sqpd75r51qqg4q5d95ss-gcc-wrapper-10.3.0/bin/cc" "-m64" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.0.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.1.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.10.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.11.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.12.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.13.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.14.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.15.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.2.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.3.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.4.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.5.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.6.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.7.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.8.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.holochain_serialized_bytes_derive.5kbehba3-cgu.9.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.7fkvjqjmij5iyj0.rcgu.o" "/build/source/target/release/deps/holochain_serialized_bytes_derive-69e20d956eab76d3.3lrkafhiajgsifng.rcgu.o" "-Wl,--as-needed" "-L" "/build/source/target/release/deps" "-L" "/nix/store/py96hafgszayhyimq2grl7hcfl71nc8q-rust-default-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/build/source/target/release/deps/libsyn-64321b2abd733e93.rlib" "/build/source/target/release/deps/libquote-b37cf6439728c439.rlib" "/build/source/target/release/deps/libproc_macro2-c63fb2c6961fe759.rlib" "/build/source/target/release/deps/libunicode_xid-43bdcc6029d2d038.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-48a8f96062ed4274.rlib" "-Wl,--start-group" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-2420485b9e5ef5e1.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-785e3cb61c4b1960.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-087191a88bdaa22d.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-9981842c02975178.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-6fb405869b015fde.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-d05c5c3c56004b7b.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-42d74d2097528b38.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-fb36534c113d2209.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-b56b9042c12b6535.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-491902d6cb3e76df.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-61834e0981b8c367.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-f78aa99d613a55bc.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-53ee54cd7fed2c57.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-544ecdbd6cda3c58.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-379cc252b6943a79.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-8063eea38dcc5e62.rlib" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-5b228734afae15ee.rlib" "-Wl,--end-group" "/nix/store/pbkz0x7svp2svzbszj79xdl5d1x08s57-rust-std-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-d6c7a399d95d173f.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/nix/store/py96hafgszayhyimq2grl7hcfl71nc8q-rust-default-1.54.0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/build/source/target/release/deps/libholochain_serialized_bytes_derive-69e20d956eab76d3.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
>   = note: /nix/store/5ddb4j8z84p6sjphr0kh6cbq5jd12ncs-binutils-2.35.1/bin/ld: final link failed: No space left on device
>           collect2: error: ld returned 1 exit status
>           
> 
> error: aborting due to previous error
> 
> error: could not compile `holochain_serialized_bytes_derive`
> 
> To learn more, run the command again with --verbose.
> warning: build failed, waiting for other jobs to finish...
> LLVM ERROR: IO failure on output stream: No space left on device
> LLVM ERROR: IO failure on output stream: No space left on device
> LLVM ERROR: IO failure on output stream: No space left on device
> LLVM ERROR: IO failure on output stream: No space left on device
> The following warnings were emitted during compilation:
> 
> warning: sqlite3/sqlite3.c:235516:1: fatal error: error writing to /build/cc0Iidpl.s: No space left on device
> warning: 235516 | SQLITE_API const char *sqlite3_sourceid(void){ return SQLITE_SOURCE_ID; }
> warning:        | ^~~~~~~~~~
> warning: compilation terminated.
> 
> error: build failed
> builder for '/nix/store/34s1aja2x5mi6csl0jgay05vli4j8jmp-holochain.drv' failed with exit code 101
> note: build failure may have been caused by lack of free disk space
> error: build of '/nix/store/34s1aja2x5mi6csl0jgay05vli4j8jmp-holochain.drv', '/nix/store/ih43qq04sz808gfbfkwvfqcyx7r960f8-holochain.drv', '/nix/store/ssk46g2xfd76q15r3ym16f816limsgs9-holochain.drv', '/nix/store/wzsd5hj4s86jpbpxknhkp06w35aj1vsv-holochain.drv' failed
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! flux@0.2.9 build-holochain: `echo "
> npm ERR! 
> npm ERR! 
> npm ERR! 
> npm ERR! This next stage will fail if Nix is not installed!! You can install here: https://nixos.wiki/wiki/Nix_Installation_Guide" && sleep 5 && nix-shell --run ./scripts/copy-hc.sh`
> [2021-11-01T06_02_27_255Z-debug.log](https://github.com/juntofoundation/flux/files/7455391/2021-11-01T06_02_27_255Z-debug.log)
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the flux@0.2.9 build-holochain script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/aia/.npm/_logs/2021-11-01T06_02_27_255Z-debug.log
 
[2021-11-01T06_02_27_255Z-debug.log](https://github.com/juntofoundation/flux/files/7455407/2021-11-01T06_02_27_255Z-debug.log)

**Comment by anaxareian** [comment]
I forgot to mention.  I am actually running BunsenLabs Linux a Debian variant and it's Bullseye version is Beryllium.

**Comment by jdeepee** [comment]
Hmmm looks like you are running out of space on the drive that is serving `/nix/*`

**Comment by anaxareian** [comment]
>$ df .>Filesystem                     1K-blocks     Used Available Use% Mounted on/dev/mapper/DellE6530--vg-home 101436416 85974536  10266104  90% /home
How jmuch room do I need?
aia--
True wisdom is less presuming than folly. 
The wise man doubteth often, and changeth his mind; 
the fool is obstinate, and doubteth not; he knoweth all things,
but his own ignorance.  

 

    On Wednesday, November 3, 2021, 10:59:20 AM EDT, Joshua Parkin ***@***.***> wrote:  
 
 


Hmmm looks like you are running out of space on the drive that is serving /nix/*

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jdeepee** [comment]
Hi @anaxareian you usually need around 20gb in my experience. Sorry for late response this slipped through the radar.

For now I will close since this is outside the scope of Flux
