### ISSUE TITLE
Flux-0.2.10.AppImage fails on 2nd restart (3rd start)

### ISSUE THREAD

**Issue by anaxareian** [juntofoundation/flux#175]
$ flux 
 App is running in production mode  

(node:2397) Warning: Accessing non-existent property 'abort' of module exports inside circular dependency
(Use `flux --trace-warnings ...` to show where the warning was created)
[2437:1103/161106.865871:ERROR:vaapi_wrapper.cc(1104)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[2437:1103/161106.866040:ERROR:vaapi_wrapper.cc(1051)] FillProfileInfo_Locked failed for va_profile VAProfileH264Main and entrypoint VAEntrypointVLD
[2437:1103/161106.866132:ERROR:vaapi_wrapper.cc(1104)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[2437:1103/161106.866192:ERROR:vaapi_wrapper.cc(1051)] FillProfileInfo_Locked failed for va_profile VAProfileH264High and entrypoint VAEntrypointVLD

UserData path
/home/aia/.config/flux

AppData path
/home/aia/.config

Log path
/home/aia/.config/flux/logs

Using Resource path
/tmp/.mount_flux721z2t/resources/packaged-resources/bin

built in language path

/tmp/.mount_flux721z2t/resources/packaged-resources/languages
%s
Init AD4M...

Starting ad4m core with path:
/home/aia/.config/flux

AD4M Bootstrap Languages:
{
  agents: 'agent-expression-store',
  languages: 'languages',
  neighbourhoods: 'neighbourhood-store'
}

Built-in languages path:
/tmp/.mount_flux721z2t/resources/packaged-resources/languages

Built-In languages:
[ 'direct-message-language' ]

=> All auto-loaded languages:
[
  'agent-expression-store',
  'languages',
  'neighbourhood-store',
  'direct-message-language'
]

Language aliases:
{
  did: 'agent-expression-store',
  lang: 'languages',
  neighbourhood: 'neighbourhood-store'
}

Resource path:
/tmp/.mount_flux721z2t/resources/packaged-resources/bin

Init services...

Init HolochainService with data path: 
/home/aia/.config/flux/ad4m/h/d
. Conductor path: 
/home/aia/.config/flux/ad4m/h/c
. Resource path: 
/tmp/.mount_flux721z2t/resources/packaged-resources/bin
Holochain ports: admin=2000 app=1337
HolochainService: Creating low-db instance for holochain-serivce
#lair-keystore-dir:"/home/aia/.config/flux/ad4m/h/c/keystore"#

#lair-keystore-ready#
#lair-keystore-version:0.0.7#

Nov 03 16:11:07.943  INFO holochain::conductor::conductor::builder: self.config=ConductorConfig { environment_path: EnvironmentRootPath("/home/aia/.config/flux/ad4m/h/c"), use_dangerous_test_keystore: false, dpki: None, keystore_path: Some("/home/aia/.config/flux/ad4m/h/c/keystore"), passphrase_service: DangerInsecureFromConfig { passphrase: "foobar" }, admin_interfaces: Some([AdminInterfaceConfig { driver: Websocket { port: 2000 } }]), network: Some(KitsuneP2pConfig { transport_pool: [Proxy { sub_transport: Quic { bind_to: None, override_host: None, override_port: None }, proxy_config: RemoteProxyClient { proxy_url: Url2 { url: "kitsune-proxy://SYVd4CF3BdJ4DS7KwLLgeU3_DbHoZ34Y-qroZ79DOs8/kitsune-quic/h/165.22.32.11/p/5779/--" } } }], bootstrap_service: Some(Url2 { url: "https://bootstrap-staging.holo.host/" }), tuning_params: KitsuneP2pTuningParams { gossip_strategy: "sharded-gossip", gossip_loop_iteration_delay_ms: 1000, gossip_outbound_target_mbps: 0.5, gossip_inbound_target_mbps: 0.5, gossip_historic_outbound_target_mbps: 0.1, gossip_historic_inbound_target_mbps: 0.1, gossip_peer_on_success_next_gossip_delay_ms: 60000, gossip_peer_on_error_next_gossip_delay_ms: 300000, gossip_local_sync_delay_ms: 60000, gossip_dynamic_arcs: false, gossip_single_storage_arc_per_space: false, default_rpc_single_timeout_ms: 30000, default_rpc_multi_remote_agent_count: 3, default_rpc_multi_remote_request_grace_ms: 3000, agent_info_expires_after_ms: 1200000, tls_in_mem_session_storage: 512, proxy_keepalive_ms: 120000, proxy_to_expire_ms: 300000, concurrent_limit_per_thread: 4096, tx2_quic_max_idle_timeout_ms: 30000, tx2_pool_max_connection_count: 4096, tx2_channel_count_per_connection: 16, tx2_implicit_timeout_ms: 30000, tx2_initial_connect_retry_delay_ms: 200 }, network_type: QuicBootstrap }), db_sync_level: Normal }
Nov 03 16:11:07.956  WARN holochain::conductor::conductor::builder: USING INSECURE PASSPHRASE FROM CONFIG--This defeats the whole purpose of having a passphrase. (unfortunately, there isn't another option at the moment).

Nov 03 16:11:08.883  INFO holochain_sqlite::schema: database initialized: Conductor
Nov 03 16:11:08.883  INFO holochain_sqlite::schema: database initialized: Wasm
Nov 03 16:11:08.919  INFO kitsune_p2p_transport_quic::tx2: bound local endpoint (quic) local_cert=Cert(VMEG7L..QERS-E) url=kitsune-quic://10.0.0.64:34151
Nov 03 16:11:08.919  INFO kitsune_p2p::spawn::actor: this_addr: kitsune-proxy://VMEG7Lzx6C8_6bLvPiR65dgUfz6eYVF61Tyt1QERS-E/kitsune-quic/h/165.22.32.11/p/5779/--
Nov 03 16:11:08.962  INFO kitsune_p2p_transport_quic::tx2: established outgoing connection (quic) local_cert=Cert(VMEG7L..QERS-E) peer_cert=Cert(SYVd4C..79DOs8) url=kitsune-quic://165.22.32.11:5779
Nov 03 16:11:08.962  INFO kitsune_p2p_types::tx2::tx2_pool_promote: establish outgoing connection (pool) elapsed_s=0.043163992 local_cert=Cert(VMEG7L..QERS-E) peer_cert=Cert(SYVd4C..79DOs8) url=kitsune-quic://165.22.32.11:5779

Nov 03 16:11:09.012  WARN kitsune_p2p::spawn::actor: received gossip for unhandled space: KitsuneSpace(0x544f2cd5c8ef123a7348e44f243bdcc0a5729a2a61f9c3f6a467d03cf5cc714e6164fdd0)

Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
Swarm listening on /ip4/10.0.0.64/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
Swarm listening on /ip4/192.168.100.213/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
Swarm listening on /ip4/10.11.12.16/tcp/4002/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/12D3KooWJvtgarwezqHUYZ5CMZSEsVFeRXZjENTFQk9Tvnuv2yYx
IPFS Version:
0.10.8
FATAL PANIC PanicInfo {
    payload: Any { .. },
    message: Some(
        Could not initialize Conductor from configuration: InterfaceError(WebsocketError(Io(Os { code: 98, kind: AddrInUse, message: "Address already in use"
 }))),
    ),
    location: Location {
        file: "crates/holochain/src/bin/holochain/main.rs",
        line: 139,
        col: 10,
    },
}

Well, this is embarrassing.

holochain had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-96a81158-5145-4300-9cf3-9361c20b26d6.toml". Submit an issue or email with the subject of "holochain Crash Report" and include the report as an attachment.

- Homepage: https://github.com/holochain/holochain
- Authors: Holochain Core Dev Team <devcore@holochain.org>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!

^Cbefore-quit SIGNAL
Unhandled Rejection at: Promise
Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'webContents')
      at /tmp/.mount_flux721z2t/resources/app.asar/background.js:2:409556
      at l (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:205397)
      at Generator._invoke (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:205150)
      at Generator.next (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:205760)
      at l (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397580)
      at s (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397783)
      at /tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397842
      at new Promise (<anonymous>)
      at App.<anonymous> (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397723)
      at App.emit (node:events:394:28)
}
reason:
TypeError: Cannot read properties of undefined (reading 'webContents')
    at /tmp/.mount_flux721z2t/resources/app.asar/background.js:2:409556
    at l (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:205397)
    at Generator._invoke (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:205150)
    at Generator.next (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:205760)
    at l (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397580)
    at s (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397783)
    at /tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397842
    at new Promise (<anonymous>)
    at App.<anonymous> (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397723)
    at App.emit (node:events:394:28)
(node:2397) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'webContents')
    at /tmp/.mount_flux721z2t/resources/app.asar/background.js:2:409556
    at l (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:205397)
    at Generator._invoke (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:205150)
    at Generator.next (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:205760)
    at l (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397580)
    at s (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397783)
    at /tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397842
    at new Promise (<anonymous>)
    at App.<anonymous> (/tmp/.mount_flux721z2t/resources/app.asar/background.js:2:397723)
    at App.emit (node:events:394:28)
(node:2397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 32)
will-quit SIGNAL

Holochain .tom extension changed to .txt so it can be uploaded here. 
[report-96a81158-5145-4300-9cf3-9361c20b26d6.txt](https://github.com/juntofoundation/flux/files/7470479/report-96a81158-5145-4300-9cf3-9361c20b26d6.txt)

**Comment by anaxareian** [comment]
Finally realized several holochain processes were running in the background.  

I was able to restart after that, presumably because the ports were available. 

My bad for not readling through the logs first.  The holochain for report had me filing issues before I looked through the logs myself.

**Comment by kaichaosun** [comment]
Great, I will close the issue then.
