### ISSUE TITLE
Bug in Release v0.2.10 - Linux AppImage version

### ISSUE THREAD

**Issue by solarpunked** [juntofoundation/flux#178]
Hi, excited that you've got to the stage that the public can test your Holochain version.

Just ran the Linux AppImage version and got the error on the following screencap (please note it's not possible to copy and paste the error message on the Linux version at least and hence the screen cap):

`
![Screenshot from 2021-11-08 19-47-53](https://user-images.githubusercontent.com/45199352/140711456-ca6df5a8-f90b-4544-9b6a-dc3b5f13a5db.png)

Here's is the debug.log as well

[debug.log](https://github.com/juntofoundation/flux/files/7495457/debug.log)

`

**Comment by fayeed** [comment]
@solarpunked Could you also share what Linux distro are you using?

**Comment by solarpunked** [comment]
Hi @fayeed I'm using Ubuntu 21.10

**Comment by jdeepee** [comment]
This should be fixed in our up-coming 0.2.12 release, closing for now and will re-open if the issue occurs again
